hardware_params:
  pmax:
    - 1.68
    - 1.68
    - 1.68
    - 1.68
    - 1.68
    - 1.68
    - 4.0
    - 4.0
    - 1.0

  pmin:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

  digit_max:
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 255
    - 4095

  digit_min:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0


    